# Generated by Django 4.1.7 on 2023-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Frontend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("imageAddress", models.CharField(max_length=300)),
            ],
        ),
    ]
