# Generated by Django 4.1.7 on 2023-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_blog_delete_frontend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
