# Generated by Django 4.1.7 on 2023-03-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_blogger_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blogger",
        ),
    ]
