# Generated by Django 4.1.7 on 2023-03-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_remove_blog_user_blogger"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blogger",
        ),
    ]
