# Generated by Django 4.1.7 on 2023-03-01 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0013_profil_delete_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profil",
            new_name="Profile",
        ),
    ]
