# Generated by Django 4.1.7 on 2023-03-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0017_remove_blog_username_blog_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="userName",
            new_name="username",
        ),
    ]
