# Generated by Django 4.1.7 on 2023-03-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0019_alter_blog_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="imageAdd",
        ),
    ]
